# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "microformats_helper"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ricardo Shiota Yasuda"]
  s.date = "2013-06-20"
  s.description = "Helper to render microformats structures (eg hcard)."
  s.email = ["shadow11@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "lib/microformats_helper.rb",
    "lib/microformats_helper/helpers.rb"
  ]
  s.homepage = "http://github.com/shadow11/microformats_helper/tree/master"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Helper to render microformats structures (eg hcard)."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

